# Promise

섹션: HTTP 통신 라이브러리-axios
수강일: 2022년 9월 22일
진행도: 1

[자바스크립트 Promise 쉽게 이해하기](https://joshua1988.github.io/web-development/javascript/promise-for-beginners/)

---

# Promise

<aside>
💡 **“A promise is an object that may produce a single value some time in the future”**
프로미스는 미래의 어느 시점에서 단일 값을 생성할 수 있는 객체이다.

</aside>

자바스크립트 비동기 처리에 사용되는 객체이다.

주로 서버에서 받아온 데이터를 화면에 표시할때 사용한다. 

---

# Promise 코드

다음은 jquery의 ajax 통신 API를 이용해 지정된 url에서 1번 상품 데이터를 받아오는 코드다.

비동기 처리를 위해 `콜백함수`를 사용했다.

```jsx
function getData(callbackFunc) {
  $.get('url 주소/products/1', function(response) {
    callbackFunc(response); // 서버에서 받은 데이터 response를 callbackFunc() 함수에 넘겨줌
  });
}

getData(function(tableData) {
  console.log(tableData); // $.get()의 response 값이 tableData에 전달됨
});
```

위 코드에 `프로미스`를 적용하면 다음과 같다.

```jsx
function getData(callback) {
  // new Promise() 추가
  return new Promise(function(resolve, reject) {
    $.get('url 주소/products/1', function(response) {
      // 데이터를 받으면 resolve() 호출
      resolve(response);
    });
  });
}

// getData()의 실행이 끝나면 호출되는 then()
getData().then(function(tableData) {
  // resolve()의 결과 값이 여기로 전달됨
  console.log(tableData); // $.get()의 reponse 값이 tableData에 전달됨
});
```

### ✔ Promise의 3가지 상태(states)

프로미스를 사용할때 알아야 하는 가장 기본적인 개념이다.

`프로미스의 상태`란 `프로미스의 처리과정`을 의미한다.

![Untitled](Promise%20cc624baf9f544b4dbf5f2687b9211093/Untitled.png)

`new Promise()`로 프로미스를 생성하고 종료할때까지 3가지 상태를 갖는다.

- `Pending(대기)` : 비동기 처리 로직이 아직 완료되지 않은 상태. 이행도 거부도 아닌 초기 상태
- `Fulfilled(이행)` : 비동기 처리가 완료되어 프로미스가 결과 값을 반환해준 상태. 작업이 성공적으로 완료되었음을 의미
- `Rejected(실패)` : 비동기 처리가 실패하거나 오류가 발생한 상태

### ✔ Pending(대기)

`new Promise()`메서드를 호출하면 대기(Pending) 상태가 된다.

```jsx
new Promise();
```

`new Promise()`메서드를 호출할때 콜백 함수를 선언할 수 있고, 콜백 함수의 인자는 `resolve`, `reject`이다.

```jsx
new Promise(function(resolve, reject) {
  // ...
});
```

### ✔ Fulfilled(이행)

콜백 함수의 인자 `resolve`를 다음과 같이 실행하면 이행(Fulfillled) 상태가 된다.

프로미스의 `이행` 상태는 `완료`상태로 볼수도 있다.

```jsx
new Promise(function(resolve, reject) {
  resolve();
});
```

이행 상태가 되면 `then()`을 이용해 처리 결과 값을 받을수 있다.

```jsx
function getData() {
  return new Promise(function(resolve, reject) {
    var data = 100;
    resolve(data);
  });
}

// resolve()의 결과 값 data를 resolvedData로 받음
getData().then(function(resolvedData) {
  console.log(resolvedData); // 100
});
```

### ✔ Rejected(실패)

`new Promise()`로 프로미스 객체 생성시 콜백 함수 인자로 `resolve`와 `reject`를 사용할 수 있는데, 이중 reject를 호출하면 실패(Rejected)상태가 된다.

```jsx
new Promise(function(resolve, reject) {
  reject();
});

// reject()의 결과 값 Error를 err에 받음
getData().then().catch(function(err) {
  console.log(err); // Error: Request is failed
});
```

실패상태가 되면 실패한 이유(실패 처리의 결과 값)을 `catch()`로 받을 수 있다.

### ✔ 프로미스 코드 예제

```jsx
function getData() {
	return new Promise(function(resolve, reject) { // 1. 프로미스 생성 : Pending(대기)상태
		$.get('url 주소/products/1', function(response) {
		if (response) {
			resolve(response); // 2-1. Fulfilled(이행)상태
		}
		reject(new Error("Request is failed"));  // 3-1. Rejected(실패) 상태
		});
	});
}

// 위 $.get() 호출 결과에 따라 'response' 또는 'Error' 출력
getData().then(function(data) { // 2-2. Fulfilled(이행)상태 → resolve의 처리 결과값 : data
	console.log(data); // response 값 출력
}).catch(function(err) {  // 3-2. 3-1. Rejected(실패) 상태 → reject의 실패 처리 결과 값 : err
	console.error(err); // Error 출력
});
```

서버에서 제대로 응답을 받아올경우 `resolve()` 메서드를 호출하고, 응답이 없으면 `reject()`메서드를 호출한다.

호출된 메서드에 따라 성공시 `then()`을 호출하고, 실패시 `catch()`를 호출해 응답 결과 또는 오류를 출력한다.

---

# 여러 개의 프로미스 연결하기 (Promise Chaining)

프로미스는 여러개의 프로미스를 연결하여 사용할 수 있다.

프로미스가 서버에서 통신이 성공했을때 `then()`메서드를 호출하고 나면 새로운 프로미스가 반환되기때문에 반환된 프로미스는 당연히 `.then()`을 호출할수있다.

```jsx
function getData() {
  return new Promise({
    // ...
  });
}

getData()
  .then(function(data) { // then() 으로 여러 개의 프로미스를 연결한 형식
    // ...
  })
  .then(function() {
    // ...
  })
  .then(function() {
    // ...
  });
```

### ✔ 프로미스 체이닝 예제

```jsx
new Promise(function(resolve, reject){ // 1. 
  setTimeout(function() { //2. resolve(1)
    resolve(1);
  }, 2000);
})
.then(function(result) { // 3.
  console.log(result); // = 1
  return result + 10; // → return(11)
})
.then(function(result) {  // 4.
  console.log(result); // = 11 
  return result + 20;  // → return(31)
})
.then(function(result) { // 5.
  console.log(result); // 6. = 31
});
```

![Untitled](Promise%20cc624baf9f544b4dbf5f2687b9211093/Untitled%201.png)

위 코드는 다음과 같은 순서로 진행된다.

1. 프로미스 객체 `new Promise()`를 하나 생성
2. `setTimeout()`을 이용해 2초후에 `resolve()`를 호출
3. `resolve()`호출시 프로미스가 **대기 → 이행** 상태로 넘어가기때문에 첫번째 `.then()`으로 넘어감
4. 첫번째 `.then()`에서 이행된 결과 값인 1을 받아 10을 더한 후 그 다음 `.then()`으로 넘겨줌
5. 두번째 `.then()`에서도 마찬가지로 이전 결과값인 11을 받아 20을 더해 다음 `.then()`으로 넘겨줌
6. 마지막 `.then()`에서 최종 결과값 31을 출력

### ✔ 프로미스 체이닝 예제 : 로그인 인증 로직

다음은 페이지에 입력된 사용자 정보를 받아와 파싱, 인증등의 작업을 거치는 코드이다. 

여러개의 프로미스를 `.then()`으로 연결하여 처리할 수 있다.

```jsx
getData(userInfo) // 사용자 정보가 담긴 객체
	// 프로미스를 반환해주는 함수
  .then(parseValue)
  .then(auth)
  .then(diaplay);

// 프로미스 체이닝
var userInfo = {
  id: 'test@abc.com',
  pw: '****'
};

function parseValue() {
  return new Promise({ // 1.
    // ...
  });
}
function auth() {
  return new Promise({
    // ...
  });
}
function display() {
  return new Promise({
    // ...
  });
}
```

---

# Promise 에러 처리 방법

### ✔ then()의 두번째 인자로 에러를 처리

```jsx
getData().then(
  handleSuccess,
  handleError
);
```

### ✔ catch()를 이용

```jsx
getData().then().catch();
```

프로미스 에러 처리 방법들은 프로미스의 `reject()` 메서드가 호출되어 실패 상태가 된 경우에 실행된다.

즉, 프로미스의 로직이 정상적으로 돌아가지 않는 경우 호출된다.

```jsx
function getData() {
  return new Promise(function(resolve, reject) {
    reject('failed');
  });
}

// 1. then()의 두 번째 인자로 에러를 처리하는 코드
getData().then(function() {
  // ...
}, function(err) {
  console.log(err);
});

// 2. catch()로 에러를 처리하는 코드
getData().then().catch(function(err) {
  console.log(err);
});
```

프로미스 에러를 처리하는 두가지 방법중, 가급적 `catch()`로 에러를 처리하는것이 더 효율적이다.

**then()의 두번째 인자로 에러를 처리하는 경우**에는 `getData()`함수의 프로미스에서 `resolve()`메서드를 호출해 정상적으로 로직을 처리했음에도 `.then()` 첫번째 콜백 함수 내부에서 오류가 나는 경우의 오류를 제대로 잡아내지 못한다.

따라서 **[Uncatcht Error(에러를 잡지 못했습니다)](https://joshua1988.github.io/images/posts/web/javascript/then-not-handling-error.png)** 오류가 발생한다.

하지만 **catch()를 사용해 처리하는 경우**에는 발생한 에러를 [정상적으로 처리](https://joshua1988.github.io/images/posts/web/javascript/catch-handling-error.png)할 수 있다.

**따라서, 더 많은 예외 처리 상황을 위해 프로미스의 끝에 가급적 catch()를 붙여 사용하는것이 좋다.**

---

# References.

[Promise - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)

[프라미스 체이닝](https://ko.javascript.info/promise-chaining)

[Promise - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)